### PR TITLE
alter aria-expanded attributes for popover invokers

### PR DESCRIPTION
**Pull request by keithamus**
Native popover in Chrome exposes "expanded" accessibility info for popover invokers, which allows assistive technologies to know that the button will expand some kind of dialog or menu.

This PR adds `aria-expanded=false` on all popover invoker buttons that target an `auto` popover, during page load or insertion into the DOM, and when a popover becomes visible, it will toggle `aria-expanded=true` for all invokers of a visible popover.

### CODE REVIEW

**Review by jgerigmeyer — APPROVED** [review]
Looks good! Two thoughts:

1. Would it make sense to expand the README documentation to mention e.g. `aria-expanded="false"`?
2. Could you update the CHANGELOG to add this change?

**Comment by keithamus** [comment]
Actually this might need rethinking a little, because it interferes with the native behaviour (as aria-expanded is then fixed to `"false"` in supported browsers)

**Comment by keithamus** [comment]
This has been updated so that it sets `aria-expanded` on all button/input elements that are invokers for a `popover=auto`.

**Review by jgerigmeyer — APPROVED** [review]

**Comment by keithamus** [comment]
@jgerigmeyer shall I add a version bump commit?

**Comment by jgerigmeyer** [comment]
> @jgerigmeyer shall I add a version bump commit?

Go ahead and merge -- I'll do a version bump and release this afternoon 👍

**Pull request merged**
